const images = {
    logo: require('./main-logo.png'),
    searchIcon: require('./search-icon.png'),
    homeIcon: require('./home-icon.png'),
    accountIcon: require('./account-icon.png'),
    astraIcon: require('./astra-icon.png'),
    cartIcon: require('./cart-icon.png'),
    locationIcon: require('./location-icon.png'),
    freeshipIcon: require('./freeship.png'),
    nextIcon: require('./next-icon.png'),
    nowShip: require('./now-ship.png'),
    astraSave: require('./astra-save.png'),
    articleSidebar: require('./article-sidebar.jpg'),
    radioIcon: require('./radio-icon.png'),
    radioCheckedIcon: require('./radio-checked-icon.png'),
    nextImage: require('./next-img.png'),
    product: require('./product.jpg'),
    prevDisablePage: require('./prevDisablePage.png'),
    nextActivePage: require('./nextActivePage.png'),
    threeDot: require('./ThreeDot.png'),
    boCongThuong: require('./bo-cong-thuong-2.png'),
    qrcode: require('./qrcode.png'),
    appstore: require('./appstore.png'),
    playstore: require('./playstore.png'),
    trusted: require('./trusted.png'),
    official: require('./official.png'),
    freeshipSlide: require('./freeship-slide.png'),
    dealSlide: require('./deal-slide.png'),
    astraBonus: require('./astra-bonus.png'),
    closeIcon: require('./close-icon.png'),
};

export default images;
